#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
# GOVINDA v8 — VM Bootstrap Script
# Runs automatically on first boot via cloud-init
# Sets up: Python venv, app code, systemd services, crontab
# ═══════════════════════════════════════════════════════════════════

set -euxo pipefail
LOG="/var/log/govinda-bootstrap.log"
exec > >(tee -a "$LOG") 2>&1

echo "=== GOVINDA Bootstrap Start: $(date) ==="

# ── System packages ───────────────────────────────────────────────
apt-get update -y && apt-get upgrade -y
apt-get install -y \
    python3.11 python3.11-venv python3.11-dev python3-pip \
    git curl wget unzip jq htop tmux \
    build-essential libssl-dev libffi-dev \
    nginx cron logrotate

# ── App user & directories ────────────────────────────────────────
id govinda &>/dev/null || useradd -m -s /bin/bash govinda

APP_DIR="/opt/govinda"
VENV_DIR="$APP_DIR/venv"
LOG_DIR="$APP_DIR/logs"
DATA_DIR="$APP_DIR/data"
MODEL_DIR="$APP_DIR/models"
MLRUNS_DIR="$APP_DIR/mlruns"

mkdir -p "$APP_DIR" "$LOG_DIR" "$DATA_DIR" "$MODEL_DIR" "$MLRUNS_DIR"
chown -R govinda:govinda "$APP_DIR"

# ── Python virtual environment ────────────────────────────────────
python3.11 -m venv "$VENV_DIR"
source "$VENV_DIR/bin/activate"
pip install --upgrade pip wheel setuptools

# ── Install dependencies (requirements.txt will be placed by deploy) ──
# App code is deployed after bootstrap via deploy.sh
# This is just the environment setup

echo "=== Bootstrap: packages done ==="

# ── Azure CLI (for Key Vault access during deploy) ────────────────
curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# ── Systemd service: Trading Engine ──────────────────────────────
cat > /etc/systemd/system/govinda-engine.service << 'UNIT'
[Unit]
Description=GOVINDA NIFTY AI Trading Engine v8
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=govinda
WorkingDirectory=/opt/govinda/app
Environment="GOVINDA_ENV=production"
EnvironmentFile=/opt/govinda/.env
ExecStartPre=/opt/govinda/scripts/load-secrets.sh
ExecStart=/opt/govinda/venv/bin/python main.py
Restart=on-failure
RestartSec=30
StandardOutput=append:/opt/govinda/logs/engine.log
StandardError=append:/opt/govinda/logs/engine-error.log

[Install]
WantedBy=multi-user.target
UNIT

# ── Systemd service: Dashboard ────────────────────────────────────
cat > /etc/systemd/system/govinda-dashboard.service << 'UNIT'
[Unit]
Description=GOVINDA Streamlit Dashboard
After=network-online.target

[Service]
Type=simple
User=govinda
WorkingDirectory=/opt/govinda/app
Environment="GOVINDA_ENV=production"
EnvironmentFile=/opt/govinda/.env
ExecStart=/opt/govinda/venv/bin/streamlit run dashboard/app.py \
          --server.port=8501 --server.address=0.0.0.0 \
          --server.headless=true --browser.gatherUsageStats=false
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable govinda-engine govinda-dashboard

# ── Script to load secrets from Key Vault ─────────────────────────
mkdir -p /opt/govinda/scripts
cat > /opt/govinda/scripts/load-secrets.sh << 'SCRIPT'
#!/bin/bash
# Load secrets from Azure Key Vault into /opt/govinda/.env
# Uses VM managed identity — no stored credentials needed

KV_URL=$(cat /opt/govinda/.kv-url 2>/dev/null || echo "")
if [ -z "$KV_URL" ]; then
    echo "Key Vault URL not set — using existing .env"
    exit 0
fi

get_secret() {
    az keyvault secret show --vault-name "$1" --name "$2" --query value -o tsv 2>/dev/null || echo ""
}

KV_NAME=$(basename "$KV_URL" .vault.azure.net | sed 's|https://||')
ENV_FILE="/opt/govinda/.env"

echo "# Generated by load-secrets.sh at $(date)" > "$ENV_FILE"
echo "GOVINDA_ENV=production"                    >> "$ENV_FILE"
echo "AZURE_KEY_VAULT_URL=$KV_URL"              >> "$ENV_FILE"
echo "DATA_DIR=/opt/govinda/data"               >> "$ENV_FILE"
echo "MODEL_DIR=/opt/govinda/models"            >> "$ENV_FILE"
echo "LOG_DIR=/opt/govinda/logs"                >> "$ENV_FILE"
echo "MLFLOW_TRACKING_URI=/opt/govinda/mlruns"  >> "$ENV_FILE"

for SECRET_NAME in \
    ANTHROPIC-API-KEY \
    OPENAI-API-KEY \
    GEMINI-API-KEY \
    DHAN-CLIENT-ID \
    DHAN-ACCESS-TOKEN \
    FYERS-APP-ID \
    FYERS-ACCESS-TOKEN \
    TELEGRAM-BOT-TOKEN \
    TELEGRAM-CHAT-ID \
    TRADING-CAPITAL \
    AZURE-STORAGE-CONNECTION-STRING; do
    VAL=$(get_secret "$KV_NAME" "$SECRET_NAME")
    if [ -n "$VAL" ]; then
        ENV_VAR=$(echo "$SECRET_NAME" | tr '-' '_')
        echo "${ENV_VAR}=${VAL}" >> "$ENV_FILE"
    fi
done

chmod 600 "$ENV_FILE"
chown govinda:govinda "$ENV_FILE"
echo "Secrets loaded from Key Vault: $KV_NAME"
SCRIPT

chmod +x /opt/govinda/scripts/load-secrets.sh
chown govinda:govinda /opt/govinda/scripts/load-secrets.sh

# ── Daily reboot 3 AM (fresh state, clears memory leaks) ──────────
echo "0 3 * * * govinda /sbin/reboot" >> /etc/crontab

echo "=== GOVINDA Bootstrap Complete: $(date) ==="
echo "Next: run azure/scripts/deploy.sh to push the application code"
